### ISSUE TITLE
代码封装提取的一个问题

### ISSUE THREAD

**Issue by 2625180201** [Lin-WangCheng/AutoWrite#1]
某个方法写得太长了，现在想做一个规范，某个方法超过x行后，就自动截取后面的代码进行封装并调用，这个要怎么实现？

**Comment by LinWanCen** [comment]
可以用 https://github.com/javaparser/javaparser 解析代码的AST语法树修改。
不过你这个不建议用工具自动完成，因为提取方法还是需要按逻辑去分析，然后手动提取比较好。
在 Intellij IDEA 可以选中需要提取的行用右键菜单或快捷键提取方法。

**Comment by 2625180201** [comment]
你有做过类似的需求吗？有没有相关api可借鉴的，我周末看了下，只能按某种代码块提出，但是用到的参数（eg:mylogic(String a,X x)）似乎没有没有很好的办法可以知道具体要传那些参数？

**Comment by LinWanCen** [comment]
没有做过类似的需求，我想这是相当复杂的，如果让我去做我可能会去 IDEA 社区版找下他们是怎么实现的，或者找到调用的API。
这里帮你找了下：https://github.com/JetBrains/intellij-community/tree/ba678ca53c292bd4c6ce877bbc569f73902bb1c6/java/java-impl/src/com/intellij/refactoring/extractMethod

**Comment by 2625180201** [comment]
好的，谢谢，我自己研究一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"林万程"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 上午8:18
收件人:&nbsp;"LinWanCen/AutoWrite"<AutoWrite@noreply.github.com&gt;;
抄送:&nbsp;"@让我一个人躲一躲"<2625180201@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LinWanCen/AutoWrite] 代码封装提取的一个问题 (#1)





 
没有做过类似的需求，我想这是相当复杂的，如果让我去做我可能会去 IDEA 社区版找下他们是怎么实现的，或者找到调用的API。
 这里帮你找了下：https://github.com/JetBrains/intellij-community/tree/ba678ca53c292bd4c6ce877bbc569f73902bb1c6/java/java-impl/src/com/intellij/refactoring/extractMethod
